# -*- coding: utf-8 -*-
"""IMDB rating analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GahAlvUNBjDqteRhSBlNfIAerJCvK445
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from IPython.display import display

data = pd.read_csv("/content/imdb_top_1000.csv")

"""#Data Cleaning of 1000 movies"""

# No. of movies listed in the data
row = data.shape[0]
print(row)

# Checking of Data

data.info()

# fix the Certificate line items issue. replacing blank cell with R
data["Certificate"] = data["Certificate"].fillna("R")

certificate_count = data["Certificate"].value_counts()
print(certificate_count)

# fix the Meta score/ Gross line items issue. replacing blank cell with mean value
data["Meta_score"] = data["Meta_score"].fillna(np.mean)
data["Gross"] = data["Gross"].fillna(np.mean)

"""#Data Sorting and Visualization"""

# IMDB rating wise Bar chart
Rating_Counts = data["IMDB_Rating"].value_counts()

plt.figure(figsize=(8,6))
plt.title("Numbers of movies with top IMDB Rating")
ax = sns.barplot(x=Rating_Counts.index, y=Rating_Counts.values)

for p in ax.patches:
    ax.annotate(f'{int(p.get_height())}',
                (p.get_x() + p.get_width() / 2., p.get_height()),
                ha='center', va='bottom', fontsize=12)
plt.xlabel("IMDB_Rating")
plt.ylabel("No. of Movies")
plt.show()

# No of A, U, UA, U/A, Unrated in which years

data["Released_Year"] = data["Released_Year"].replace("PG", 1995)

data["Released_Year"] = pd.to_numeric(data["Released_Year"], errors ='coerce')


bins = range(int(data["Released_Year"].min()), int(data["Released_Year"].max()) + 10, 10)
labels = [f"{i}-{i+9}" for i in bins[:-1]]  # Create labels like '1990-1999', '2000-2009', etc.


# Bin the 'Year' column
data['Year_Binned'] = pd.cut(data['Released_Year'], bins=bins, labels=labels, right=False)



table = data.pivot_table(index="Year_Binned", columns="Certificate", aggfunc="size", fill_value=0, observed=False)

styled_pivot = table.style.set_caption("Number of Movies by Certificate and Year Bin")\
                                .set_table_styles([{'selector': 'thead th',
                                                    'props': [('background-color', 'lightblue'),
                                                              ('font-weight', 'bold')]}])



display(styled_pivot)

# line chart of cerificate and years

certificate_of_most_IMDB = ["A", "PG-13", "R", "U", "UA"]
Extracted_data = table[certificate_of_most_IMDB].copy()

Extracted_data["Total"] = Extracted_data.sum(axis=1)

display(Extracted_data)

"""#Observations:

1. Most Common Certificates: You can see how certificates like 'U' (Universal) were more prevalent in earlier decades, while certificates like 'R' and 'PG-13' became more common in later years.
2. Trends Over Decades: There is a noticeable increase in the number of movies per decade, especially in the 2000-2009 and 2010-2019 periods.
3. Increased Specialization: From the 1980s onward, there has been a shift towards more specific age categories, such as 'PG-13' and 'R' ratings.
"""